### ISSUE TITLE
Unclear Minimal Documents

### ISSUE THREAD

**Issue by rodmachen** [CollaborareDotNet/innersourceadventure#1]
In the "Generate Minimal Documents" section, it asks for "the four minimal documents that every InnerSource project should have in its repository."

I've searched `https://paypal.github.io/InnerSourceCommons/` (as well as Googling relevant keywords) but can't find any reference to these. 

Is there a way to point the user to this information?

**Comment by cdnadmin** [comment]
As you know @rodmachen , this is a substantial work in progress.  But, [v1.2.0+](https://www.npmjs.com/package/innersourceadventure) of this workshopper now has more details/hints to solve the problems presented.  There's still much work to be done, but hopefully, v1.2.0 will answer your question above.  ;-) 

I'll let you venture and if you still have questions, we can discuss in [tomorrow's meetup](https://www.meetup.com/ATXNodeSchool/events/235615843/)!

**Comment by rodmachen** [comment]
New text definitely gives me what I need.

Closing issue.
